=== AlterFalter/XML-Project/src/database/Noten-DB.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

   <xs:element name="Prüfungen">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Prüfung" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Prüfung">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="SchülerIn" maxOccurs="unbounded" />
            </xs:sequence>
			<xs:attribute name ="Datum" type="xs:date" use="required"/>
			<xs:attribute name ="Name" type="xs:string" use="required"/>
			<xs:attribute name ="Fach" type="xs:string" use="required"/>
			<xs:attribute name ="Klasse" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
	
	<xs:element name="SchülerIn">
	    <xs:complexType>
		    <xs:sequence>
		        <xs:element name="Name" type="xs:string"/>
		        <xs:element name="Note" type="noteType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:simpleType name ="noteType">
	    <xs:restriction base="xs:decimal">
		    <xs:enumeration value ="1.0"/>
			<xs:enumeration value ="1.5"/>
			<xs:enumeration value ="2.0"/>
			<xs:enumeration value ="2.5"/>
			<xs:enumeration value ="3.0"/>
			<xs:enumeration value ="3.5"/>
			<xs:enumeration value ="4.0"/>
			<xs:enumeration value ="4.5"/>
			<xs:enumeration value ="5.0"/>
			<xs:enumeration value ="5.5"/>
			<xs:enumeration value ="6.0"/>
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== AlterFalter/XML-Project/src/database/Noten-DB.xml
<?xml version="1.0"?>
<Prüfungen xsi:noNamespaceSchemaLocation="Noten-DB.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Prüfung Datum="2021-01-01" Name="Addieren 1" Fach="Mathematik" Klasse="1A">
    <SchülerIn>
      <Name>Meier Karin</Name>
      <Note>6.0</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Meier Reto</Name>
      <Note>4.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Schmid Nicole</Name>
      <Note>6.0</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Keller Michael</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Gerber Mia</Name>
      <Note>4.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Weber Liam</Name>
      <Note>4.5</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Schneider Emma</Name>
      <Note>3.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Huber Noah</Name>
      <Note>4.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Meyer Sofia</Name> 
      <Note>4.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Steiner Matteo</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Favre Lara</Name>
      <Note>5.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Frei Gabriel</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Moser Emilia</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Wyss Luca</Name>
      <Note>4.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Fischer Mila</Name>
      <Note>4.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Brunner Leon</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Bucher Lina</Name>
      <Note>5.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Baumann Elias</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Zürcher Lia</Name>
      <Note>4.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Da Silva Louis</Name>
      <Note>6.0</Note>
    </SchülerIn>
  </Prüfung>
  <Prüfung Datum="2021-01-15" Name="Addieren 2" Fach="Mathematik" Klasse="1A">
    <SchülerIn>
      <Name>Meier Karin</Name>
      <Note>5.5</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Meier Reto</Name>
      <Note>3.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Schmid Nicole</Name>
      <Note>5.5</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Keller Michael</Name>
      <Note>5.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Gerber Mia</Name>
      <Note>4.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Weber Liam</Name>
      <Note>4.0</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Schneider Emma</Name>
      <Note>3.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Huber Noah</Name>
      <Note>3.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Meyer Sofia</Name> 
      <Note>4.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Steiner Matteo</Name>
      <Note>5.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Favre Lara</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Frei Gabriel</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Moser Emilia</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Wyss Luca</Name>
      <Note>4.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Fischer Mila</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Brunner Leon</Name>
      <Note>5.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Bucher Lina</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Baumann Elias</Name>
      <Note>5.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Zürcher Lia</Name>
      <Note>5.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Da Silva Louis</Name>
      <Note>6.0</Note>
    </SchülerIn>
  </Prüfung>
  <Prüfung Datum="2021-02-01" Name="Addieren 3" Fach="Mathematik" Klasse="1A">
    <SchülerIn>
      <Name>Meier Karin</Name>
      <Note>5.0</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Meier Reto</Name>
      <Note>3.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Schmid Nicole</Name>
      <Note>5.5</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Keller Michael</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Gerber Mia</Name>
      <Note>3.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Weber Liam</Name>
      <Note>5.0</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Schneider Emma</Name>
      <Note>4.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Huber Noah</Name>
      <Note>4.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Meyer Sofia</Name> 
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Steiner Matteo</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Favre Lara</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Frei Gabriel</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Moser Emilia</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Wyss Luca</Name>
      <Note>5.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Fischer Mila</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Brunner Leon</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Bucher Lina</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Baumann Elias</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Zürcher Lia</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Da Silva Louis</Name>
      <Note>6.0</Note>
    </SchülerIn>
  </Prüfung>
  <Prüfung Datum="2021-02-15" Name="Addieren 4" Fach="Mathematik" Klasse="1A">
    <SchülerIn>
      <Name>Meier Karin</Name>
      <Note>5.0</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Meier Reto</Name>
      <Note>3.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Schmid Nicole</Name>
      <Note>5.5</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Keller Michael</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Gerber Mia</Name>
      <Note>3.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Weber Liam</Name>
      <Note>5.0</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Schneider Emma</Name>
      <Note>4.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Huber Noah</Name>
      <Note>4.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Meyer Sofia</Name> 
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Steiner Matteo</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Favre Lara</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Frei Gabriel</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Moser Emilia</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Wyss Luca</Name>
      <Note>5.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Fischer Mila</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Brunner Leon</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Bucher Lina</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Baumann Elias</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Zürcher Lia</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Da Silva Louis</Name>
      <Note>6.0</Note>
    </SchülerIn>
  </Prüfung>
  <Prüfung Datum="2021-01-01" Name="Schreiben 1" Fach="Deutsch" Klasse="1A">
    <SchülerIn>
      <Name>Meier Karin</Name>
      <Note>4.5</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Meier Reto</Name>
      <Note>4.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Schmid Nicole</Name>
      <Note>4.5</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Keller Michael</Name>
      <Note>4.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Gerber Mia</Name>
      <Note>4.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Weber Liam</Name>
      <Note>5.0</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Schneider Emma</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Huber Noah</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Meyer Sofia</Name> 
      <Note>3.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Steiner Matteo</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Favre Lara</Name>
      <Note>5.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Frei Gabriel</Name>
      <Note>5.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Moser Emilia</Name>
      <Note>4.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Wyss Luca</Name>
      <Note>5.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Fischer Mila</Name>
      <Note>5.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Brunner Leon</Name>
      <Note>4.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Bucher Lina</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Baumann Elias</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Zürcher Lia</Name>
      <Note>5.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Da Silva Louis</Name>
      <Note>4.5</Note>
    </SchülerIn>
  </Prüfung>
  <Prüfung Datum="2021-01-15" Name="Schreiben 2" Fach="Deutsch" Klasse="1A">
    <SchülerIn>
      <Name>Meier Karin</Name>
      <Note>4.5</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Meier Reto</Name>
      <Note>4.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Schmid Nicole</Name>
      <Note>4.5</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Keller Michael</Name>
      <Note>4.5</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Gerber Mia</Name>
      <Note>4.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Weber Liam</Name>
      <Note>5.0</Note>
    </SchülerIn>
    <SchülerIn>
      <Name>Schneider Emma</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Huber Noah</Name>
      <Note>6.0</Note>
    </SchülerIn>
	<SchülerIn>
      <Name>Meyer Sofia</Name> 
      <Note>3.5</Note>
    </SchülerIn>
	<SchülerIn>
